// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $forbidden from "./routes/forbidden.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $redirect from "./routes/redirect.tsx";
import * as $Island from "./islands/Island.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/forbidden.tsx": $forbidden,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/redirect.tsx": $redirect,
  },
  islands: {
    "./islands/Island.tsx": $Island,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
